spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 10

hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl-auto: validate
